FROM python:3.12-slim

WORKDIR /app

COPY api/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r ./requirements.txt

COPY api/ ./api
COPY database/ ./database/

EXPOSE 5000

CMD ["python", "-m", "api.server"]